name = "upalupaServer"
author = "Nailima"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7486d819c9abc696257e6dd98ea007ae27a01be91d81645fbe0cfd0055b9e184"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
