name = "upalupaServer"
author = "Nailima"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a975255a15f6d9af229df88f3a3512f8de55c5dd1dadec95f229abd41d454bb"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
