name = "upalupaClient"
author = "Nailima"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac7cf2f9b9b2415d86d3f0bf8f9f5dadfcee21d52887f4f058ae4801182ede07"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
